### ISSUE TITLE
Respawn w świątyni do 5 lvl - zależny od miesjca startu

### ISSUE THREAD

**Issue by Nimorid** [kroniki-neverwinter/features#117]
W Neverwinter mamy darmowy respawn (WP `mf_temple_tyr`) dla low-leveli w Domu Sprawiedliwości. 

- [x] W Port Llast można zrobić w świątyni Tyra również (`ni_llastr_tyr`) - postawiłam tam analogiczny WP `mf_temple_tyr_llast`
- [x] W Luskan jest Świątynia Czerwonych Żagli (`ni_lus_umberlee`) - postawiłam tam WP `mf_temple_umb_lus`

**Comment by Mefi100** [comment]
Respawn ustawiony w zależności od miasta wybranego przy przejściu przez portal. Do przetestowania.

**Comment by Nimorid** [comment]
Działa :)
