### ISSUE TITLE
UCS - Gorgotha

### ISSUE THREAD

**Issue by Nimorid** [kroniki-neverwinter/features#2]
Ukończenie questa Gorgothy również nie wiąże się z odblokowaniem możliwości wzięcia UCSa @Mefi100 
Steps:
1. Zacznij grę bardem, rozdaj 5 poziomów, podbijając wiedzę Tajemną do min. 8
2. Weź questa od Gorgothy
3. Weź 25 leveli barba, żeby móc coś zabić XD
4. Zabij herszta goblinów
5. Oddaj klejnot Gorgocie
6. Dodaj 1 dodatkowy level i spróbuj wziąć UCSa

![Image](https://github.com/user-attachments/assets/ab5a1c93-0719-47bc-9744-c90dfe87d8e9)

**Comment by Nimorid** [comment]
@Mefi100 czy jakoś naprawiałeś to tylko u Klautha?

**Comment by Mefi100** [comment]
> @Mefi100 czy jakoś naprawiałeś to tylko u Klautha?

Tak, Gorgotha jest jeszcze TBD. Wkrótce dodam.

**Comment by Mefi100** [comment]
Poprawione w najnowszej wersji modułu.

**Comment by Nimorid** [comment]
Verified fixed.
