### ISSUE TITLE
Luskan - 1 mały quest początkowy dla graczy

### ISSUE THREAD

**Issue by Nimorid** [kroniki-neverwinter/features#45]
Dialog i ResRef NPC'a: `ni_lus_jahn`
Przedmiot do przynoszenia w nieskończoność: `hi_deadrat`

Quest ustawiony, będzie potrzeba ustawić nagrodę za donoszenie trucheł. Jako że szansa na drop jest 33%, to może 5sz za truchło? @Mefi100

**Comment by Mefi100** [comment]
nagroda za Q dodana
